### ISSUE TITLE
CodeBuildからParameterStoreに接続出来るように設定を変更する

### ISSUE THREAD

**Issue by keitakn** [nekochans/qiita-stocker-terraform#83]
# Doneの定義
- CodeBuildからParameterStoreに接続出来るようになっている事

# 補足情報
https://github.com/nekochans/qiita-stocker-backend/pull/186 を実施中にmigration用のCodeBuildからParameterStoreに接続出来ない事が判明した。

具体的には以下のエラーが発生する。

```
$ DEPLOY_STAGE=stg node createDotenv.js 
(node:265) UnhandledPromiseRejectionWarning: AwsEnvCreatorError: CredentialsError 
    at Object.exports.fetchFromParameterStore (/codebuild/output/src017872755/src/github.com/nekochans/qiita-stocker-backend/node_modules/@nekonomokochan/aws-env-creator/dist/src/fetchFromParameterStore.js:49:31) 
    at process._tickCallback (internal/process/next_tick.js:68:7) 
(node:265) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2) 
(node:265) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 
Done in 0.30s. 
```

`modules/aws/api/codebuild.tf` の `codebuild_trust_relationship` を修正すれば問題ないと思われる。

**Comment by keitakn** [comment]
@kobayashi-m42 ストーリーポイントは3を想定しているよ🐱（修正だけなら2だが動作確認も含めると3かな）

**Comment by kobayashi-m42** [comment]
@keitakn なるほど、権限の問題で実行できないんだね！ストリーポイントも3でいいと思う！🐱
